### ISSUE TITLE
Able to tech a skill that cannot be tech'd

### ISSUE THREAD

**Issue by benlei** [ben-lei/dn-maze#30]
For example: https://dnmaze.com/majesty-90/-------0K0--0-0--0330--3G5-0F0-0F2-0E0-0C0--1---0---A0---0---0--00--00--

Force Shield should be grayed out as an option

**Comment by spacem** [comment]
You say: "If you think you have knowledge on how to properly obtain all available skill IDs for weapon techs, please post your findings in https://github.com/ben-lei/dn-maze/issues"

Item stats are in tables like itemtable_X for example itemtable_cash. These tables have TypeParam columns. I still cant figure out what TypeParam2 is but TypeParam1 always points to a potentialId in a potential table. For example there is a table potentialtable_cash and it can have multiple rows for each cash shop weapon each with has different skill ids. For other items like plates there are multiple records for 3rd line stats, etc.

Potentially if you get all the skill ids from all the potential tables and combine with skill ids in itemtable_skilllevelup.dnt that is probably all the skills that can be teched maybe. gl

**Comment by benlei** [comment]
Thanks @spacem, I will look into it when I have time.

**Comment by benlei** [comment]
Here's the query I used with the dncli 2:

```
SELECT DISTINCT
    p._SkillID,
    p._SkillLevel,
    p._SkillUsingType,
    s._NameID,
    m._Message,
    s._NeedJob
FROM
    potential p
        JOIN
    skill s ON s.ID = p._SkillID
        JOIN
    message m ON m.ID = s._NameID
WHERE
    p._SkillLevel != 0 AND s._NeedJob != 0;
```

This definitely seems like a complete list of possible weapon techs. Thanks @spacem .

**Comment by benlei** [comment]
In v2 skills levels are correctly adjusted based on techs.
