### ISSUE TITLE
Use Gulp + SASS + UglifyJS to build up JS/CSS files.

### ISSUE THREAD

**Issue by benlei** [ben-lei/dn-maze#6]
Better for minimizing the CSS files. The way things should work in starting up NodeJS app is by building the JS/CSS via Gulp with SASS files, and then starting up the app.

**Comment by ben-lei** [comment]
At the moment I think it's not necessary. I was looking into it and it looks like Grunt is analogous to Rake.

Better off just using UglifyJS + SASS + something else to minify JS+CSS on startup.
